"""empty message

Revision ID: 2e9f9d7c0dbb
Revises: 
Create Date: 2018-10-16 17:32:14.064192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e9f9d7c0dbb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alamat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_pic', sa.String(length=60), nullable=True),
    sa.Column('alamat', sa.String(length=60), nullable=True),
    sa.Column('keterangan', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=128), nullable=True),
    sa.Column('tgl_terima', sa.Date(), nullable=True),
    sa.Column('is_consumable', sa.Boolean(), nullable=True),
    sa.Column('typebarang', sa.String(length=64), nullable=True),
    sa.Column('serial', sa.String(length=128), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('is_good', sa.Boolean(), nullable=True),
    sa.Column('penempatan', sa.String(length=128), nullable=True),
    sa.Column('keterangan', sa.String(length=256), nullable=True),
    sa.Column('asal', sa.Integer(), nullable=True),
    sa.Column('tujuan', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_nama'), 'inventory', ['nama'], unique=True)
    op.create_table('listreqbarang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('req_id', sa.Integer(), nullable=True),
    sa.Column('barang_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('peranan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=60), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('deskripsi', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama')
    )
    op.create_table('reqbarang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pengguna_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tmpreqbarang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pengguna_id', sa.Integer(), nullable=True),
    sa.Column('barang_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('typebarang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=60), nullable=True),
    sa.Column('keterangan', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pengguna',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=60), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('uname', sa.String(length=60), nullable=True),
    sa.Column('passwd_hash', sa.String(length=128), nullable=True),
    sa.Column('alamat', sa.String(length=60), nullable=True),
    sa.Column('peran_id', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['peran_id'], ['peranan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pengguna_email'), 'pengguna', ['email'], unique=True)
    op.create_index(op.f('ix_pengguna_nama'), 'pengguna', ['nama'], unique=False)
    op.create_index(op.f('ix_pengguna_uname'), 'pengguna', ['uname'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pengguna_uname'), table_name='pengguna')
    op.drop_index(op.f('ix_pengguna_nama'), table_name='pengguna')
    op.drop_index(op.f('ix_pengguna_email'), table_name='pengguna')
    op.drop_table('pengguna')
    op.drop_table('typebarang')
    op.drop_table('tmpreqbarang')
    op.drop_table('reqbarang')
    op.drop_table('peranan')
    op.drop_table('listreqbarang')
    op.drop_index(op.f('ix_inventory_nama'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_table('alamat')
    # ### end Alembic commands ###
