"""empty message

Revision ID: 8090c6127121
Revises: a405c1466b3e
Create Date: 2018-10-17 03:02:15.895945

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8090c6127121'
down_revision = 'a405c1466b3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listreqbarang')
    op.add_column('reqbarang', sa.Column('barang_id', sa.Integer(), nullable=True))
    op.add_column('reqbarang', sa.Column('qty', sa.Integer(), nullable=True))
    op.add_column('reqbarang', sa.Column('tgl_selesai', sa.Date(), nullable=True))
    op.add_column('reqbarang', sa.Column('tgl_terima', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reqbarang', 'tgl_terima')
    op.drop_column('reqbarang', 'tgl_selesai')
    op.drop_column('reqbarang', 'qty')
    op.drop_column('reqbarang', 'barang_id')
    op.create_table('listreqbarang',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('req_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('barang_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('qty', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
