"""empty message

Revision ID: 9aca709d82b6
Revises: cd4cfdd6fc40
Create Date: 2018-09-18 14:19:48.246427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aca709d82b6'
down_revision = 'cd4cfdd6fc40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('asal', sa.Integer(), nullable=True))
    op.add_column('inventory', sa.Column('tujuan', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inventory', 'alamat', ['asal'], ['id'])
    op.create_foreign_key(None, 'inventory', 'alamat', ['tujuan'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_column('inventory', 'tujuan')
    op.drop_column('inventory', 'asal')
    # ### end Alembic commands ###
