"""empty message

Revision ID: a387ef18b68e
Revises: 2e9f9d7c0dbb
Create Date: 2018-10-16 23:28:25.639461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a387ef18b68e'
down_revision = '2e9f9d7c0dbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inventory_nama', table_name='inventory')
    op.create_index(op.f('ix_inventory_nama'), 'inventory', ['nama'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_nama'), table_name='inventory')
    op.create_index('ix_inventory_nama', 'inventory', ['nama'], unique=True)
    # ### end Alembic commands ###
