"""empty message

Revision ID: a405c1466b3e
Revises: a387ef18b68e
Create Date: 2018-10-16 23:29:37.431347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a405c1466b3e'
down_revision = 'a387ef18b68e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'inventory', ['serial'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory', type_='unique')
    # ### end Alembic commands ###
