"""empty message

Revision ID: c0519859b449
Revises: ea850a02b142
Create Date: 2018-09-19 10:20:26.575897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0519859b449'
down_revision = 'ea850a02b142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('negara',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('propinsi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=60), nullable=True),
    sa.Column('negara', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['negara'], ['negara.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=60), nullable=True),
    sa.Column('propinsi', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['propinsi'], ['propinsi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kota')
    op.drop_table('propinsi')
    op.drop_table('negara')
    # ### end Alembic commands ###
