"""empty message

Revision ID: db62f9d20e36
Revises: 9aca709d82b6
Create Date: 2018-09-18 15:46:50.924987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'db62f9d20e36'
down_revision = '9aca709d82b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('typebarang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=60), nullable=True),
    sa.Column('keterangan', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('inventory', sa.Column('is_consumable', sa.Boolean(), nullable=True))
    op.add_column('inventory', sa.Column('is_good', sa.Boolean(), nullable=True))
    op.add_column('inventory', sa.Column('nama', sa.String(length=128), nullable=True))
    op.add_column('inventory', sa.Column('typebarang', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_inventory_nama'), 'inventory', ['nama'], unique=True)
    op.create_foreign_key(None, 'inventory', 'typebarang', ['typebarang'], ['id'])
    op.drop_column('inventory', 'type')
    op.drop_column('inventory', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('status', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('inventory', sa.Column('type', mysql.VARCHAR(length=60), nullable=True))
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_index(op.f('ix_inventory_nama'), table_name='inventory')
    op.drop_column('inventory', 'typebarang')
    op.drop_column('inventory', 'nama')
    op.drop_column('inventory', 'is_good')
    op.drop_column('inventory', 'is_consumable')
    op.drop_table('typebarang')
    # ### end Alembic commands ###
