"""empty message

Revision ID: e6cf8310fb04
Revises: e40c2380165a
Create Date: 2018-09-18 14:10:34.574593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6cf8310fb04'
down_revision = 'e40c2380165a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alamat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_pic', sa.String(length=60), nullable=True),
    sa.Column('alamat', sa.String(length=60), nullable=True),
    sa.Column('kota', sa.String(length=60), nullable=True),
    sa.Column('propinsi', sa.String(length=60), nullable=True),
    sa.Column('negara', sa.String(length=60), nullable=True),
    sa.Column('keterangan', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tgl_terima', sa.Date(), nullable=True),
    sa.Column('type', sa.String(length=60), nullable=True),
    sa.Column('serial', sa.String(length=128), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('pengirim', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=128), nullable=True),
    sa.Column('penempatan', sa.String(length=128), nullable=True),
    sa.Column('keterangan', sa.String(length=256), nullable=True),
    sa.Column('asal', sa.Integer(), nullable=True),
    sa.Column('tujuan', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asal'], ['alamat.id'], ),
    sa.ForeignKeyConstraint(['pengirim'], ['alamat.id'], ),
    sa.ForeignKeyConstraint(['tujuan'], ['alamat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory')
    op.drop_table('alamat')
    # ### end Alembic commands ###
