"""empty message

Revision ID: ea850a02b142
Revises: db62f9d20e36
Create Date: 2018-09-18 21:55:20.268091

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ea850a02b142'
down_revision = 'db62f9d20e36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('type_id', sa.Integer(), nullable=True))
    op.drop_constraint('inventory_ibfk_5', 'inventory', type_='foreignkey')
    op.drop_constraint('inventory_ibfk_2', 'inventory', type_='foreignkey')
    op.create_foreign_key(None, 'inventory', 'typebarang', ['type_id'], ['id'])
    op.drop_column('inventory', 'typebarang')
    op.drop_column('inventory', 'pengirim')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('pengirim', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('inventory', sa.Column('typebarang', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.create_foreign_key('inventory_ibfk_2', 'inventory', 'alamat', ['pengirim'], ['id'])
    op.create_foreign_key('inventory_ibfk_5', 'inventory', 'typebarang', ['typebarang'], ['id'])
    op.drop_column('inventory', 'type_id')
    # ### end Alembic commands ###
